name: API Docker Image CI
env:
  ImageName: 'ghcr.io/kmayer10/python-api:v2.${{ github.run_number }}'
on:
  push:
    branches: [ "main", "argocd-demo"  ]
    paths:
      - 'api/*'
      - '.github/workflows/docker-image-api.yml'
  pull_request:
    branches: [ "main", "argocd-demo" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build & PUSH the Docker image
      run: |
        cd api/
        docker image build . -f Dockerfile -t ghcr.io/kmayer10/python-api:v2.${{ github.run_number }}
        # docker image push ghcr.io/kmayer10/python-api:v2.${{ github.run_number }}
        cp deployment.yaml ../manifests/api/deployment.yaml
    - name: Replace string in file
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: ./manifests/api/deployment.yaml
        old-string: ImageTag
        new-string: v2.${{ github.run_number }}
    - name: Build & PUSH the Docker image
      run: |
        echo $ImageName
        git status
        cat ./manifests/api/deployment.yaml

